import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Sidebar from "../components/Sidebar";
import MainContent from "../components/MainContent";
const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Ecommerce App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Sidebar />
        <MainContent />
      </main>
    </div>
  );
};

export default Home;
