import type { NextPage } from "next";
import Head from "next/head";
import MainContent from "../components/MainContent";
import MainUi from "../components/MainUi";

const items: string[] = ["Home", "Favorite", "account", "catalog"];
const buttons: string[] = ["be premium"];
const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Ecommerce App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MainUi items={items} buttons={buttons}>
        <MainContent />
      </MainUi>
    </div>
  );
};

export default Home;
