import type { NextPage } from "next";
import Head from "next/head";
import { useDispatch, useSelector } from "react-redux";
import MainContent from "../components/mainContent/MainContent";
import MainUi from "../components/mainUi/MainUi";
import { actionTypes } from "../store/actionTypes";
import { desk } from "../components/data";
import { sofa } from "../components/data";
import { useEffect } from "react";

const items: { src: string; name: string }[] = [
  { name: "Home", src: "/" },
  { name: "Favorite", src: "/favorite" },
  { name: "account", src: "/login" },
  { name: "category", src: "/category" },
];
const buttons: string[] = ["be premium"];

const Home: NextPage = () => {
  const dispatch = useDispatch();
  const selector = useSelector((state) => state);

  useEffect(() => {
    dispatch({ type: actionTypes.SET_PRODUCT, payload: desk });
    dispatch({ type: actionTypes.SET_PRODUCT, payload: sofa });
  }, []);

  console.log(selector);

  return (
    <div>
      <Head>
        <title>Ecommerce App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MainUi items={items} buttons={buttons} title="MABELINO.">
        <MainContent />
      </MainUi>
    </div>
  );
};

export default Home;
